In [1]:
import numpy as np
import sys

In [ ]:
A = [1, 2 ,3 ,4 ,5]
B = np.array([1, 2, 3, 4, 5])

print(A)
print(B)
print(sys.getsizeof(A))
print(B.nbytes)

In [ ]:
D1 = np.array([1, 2, 3])
print(D1) 
print(D1.ndim)
print(D1.shape)

print('=======')

D2 = np.array([[1, 2, 3],[4, 5, 6]])
print(D2) 
print(D2.ndim)
print(D2.shape)

print('=======')

D3 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(D3) 
print(D3.ndim)
print(D3.shape)


In [25]:
a = [2, 3, 4]
b = [2, 3, 4]

result = a + b
print(result)

a2 = np.array([2, 3, 4])
b2 =np.array([2, 3, 4])

print(np.add(a2, b2))

[2, 3, 4, 2, 3, 4]
[4 6 8]


restart kernel

In [ ]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# print(a)
# print(a[1])
a[0,:]

array([2])

In [20]:
a[:,1]

array([2, 7])